version: '2'
services:
    php:
        build: ./docker/.
        networks:
            - frontend
            - backend 
        volumes:
            - './:/usr/share/nginx/html'
        depends_on:
            - mysql
    nginx:
        image: 'nginx:1.11'
        ports:
            - '8989:80' 
        networks:
            - frontend
        volumes:
            - './:/usr/share/nginx/html:ro'
            - './docker/nginx.conf:/etc/nginx/conf.d/default.conf'
        depends_on:
            - php
    mysql:
        image: 'mysql:5.7'
        networks:
            - backend 
        environment:
            MYSQL_ROOT_PASSWORD: hello
        volumes:
            - mysql-data:/var/lib/mysql
networks:
    frontend:
    backend:

volumes:
    mysql-data:
        driver: local


